#!/usr/bin/ruby

require 'json'

musicians = {}

# Extract placements by doing text parsing of the SVG generated by
# solver.  I really should use a proper XML library for this, but I
# ran into some weird gem installation error.
ARGF.read.scan(/<circle[^<>]*\/>/).each{|c|
   m = c.match(/id="m(\d+)_\d+"/)
   x = c.match(/cx="([^"]+)"/)
   y = c.match(/cy="([^"]+)"/)
   if m and x and y
      musicians[m[1].to_i] = {"x"=>x[1].to_f, "y"=>y[1].to_f}
   end
}

# Convert placements to list, and check that all musicians are present.
placements = []
max_musician_id = musicians.keys.max
(0 .. max_musician_id).each{|id|
   unless musicians[id]
      print "Missing musician #{id}\n"
      abort
   end

   placements += [{"x"=>musicians[id]["x"], "y"=>musicians[id]["y"]}]
}

# Output JSON.
puts JSON.generate({"placements": placements})
